# Complete Manifest Where in single yml we defined Deployment & Service for SpringApp &
#PVC(with default  StorageClass),ReplicaSet/StatefulSet & Service For Mongo.
# storage class, pv, pvc, 
# configMaps / Secretes


apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootdeployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      name: springapppod
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: jbabi/spring-boot-mongo3
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_USERNAME
          value: devdb
        - name: MONGO_DB_PASSWORD
          value: devdb@123
        - name: MONGO_DB_HOSTNAME
          value: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: springapp-svc
spec:
  selector:
    app: springboot
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30030
    type: NodePort
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodbrs
  namespace: dev
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
     metadata:
       name: mongodbpod
       labels:
         app: mongodb
     spec:
       volumes:
       - name: hostpathvol  # - name: nfsvol
                                           #   nfs
         hostPath:                #     server: <nfs-serverIP>
           path: /tmp/mongodbbkp  # /mnt/share
       containers:
       - name: mongodbcontainer
         image: mongo
         ports:
         - containerPort: 27017
         env:
         - name: MONGO_INITDB_ROOT_USERNAME
           value: devdb
         - name: MONGO_INITDB_ROOT_PASSWORD
           value: devdb@123
         volumeMounts:
         - name: hostpathvol # nfsvol
           mountPath: /data/db   
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
